export const FETCH_TECHNOLOGY_REQUEST = 'FETCH_TECHNOLOGY_REQUEST'
export const FETCH_TECHNOLOGY_SUCCESS = 'FETCH_TECHNOLOGY_SUCCESS'
export const FETCH_TECHNOLOGY_FAILURE = 'FETCH_TECHNOLOGY_FAILURE'